// src/daemon/onboarding/types.ts
// Core types for the Seamless Onboarding subsystem.
//
// A SetupSkill is generated by the LLM in response to "set me up with X".
// It's a declarative sequence of steps — open a URL, wait for clipboard,
// store in keychain, install MCP server, configure, smoke test, confirm.

import type { AutonomyTier } from '../agency/types'

/** One step in a setup flow. */
export type SetupStep =
  | { type: 'speak'; text: string }
  | { type: 'open_url'; url: string }
  | { type: 'wait_for_clipboard'; pattern: string; timeout_sec?: number; description: string }
  | { type: 'wait_for_oauth_callback'; callback_path: string; expected_param: string; timeout_sec?: number }
  | { type: 'store_keychain'; service: string; account: string; source: 'clipboard' | 'oauth' | 'literal'; literal_value?: string }
  | { type: 'install_mcp_server'; via: 'smithery' | 'npm'; package: string; smoke_args?: string[] }
  | { type: 'configure_mcp_server'; server_config: any }
  | { type: 'smoke_test_tool'; qualified_id: string; args?: Record<string, unknown>; expect_ok?: boolean }
  | { type: 'await_user_confirm'; prompt: string; default_choice?: 'yes' | 'no' }
  | { type: 'speak_on_success'; text: string }
  | { type: 'speak_on_failure'; text: string }

/** A complete setup flow for one service. Produced by the LLM. */
export type SetupSkill = {
  service_name: string
  service_display_name: string
  auth_type: 'pat' | 'oauth' | 'none'
  steps: SetupStep[]
  estimated_minutes: number
  notes?: string
}

/** Runtime state of an in-flight setup flow. */
export type FlowState = {
  flow_id: string
  service_name: string
  current_step_index: number
  started_at: number
  status: 'awaiting_user' | 'executing' | 'completed' | 'failed' | 'cancelled'
  collected_data: Record<string, unknown>
  error?: string
  completed_at?: number
}

/** OAuth capture result. */
export type OAuthCapture = {
  callback_path: string
  query_params: Record<string, string>
  raw_url: string
  captured_at: number
}

/** Communication channel between the setup flow and the user.
 *  C.2.5 uses 'inbox' (writes to ~/.kairos/onboarding-chat.md). Phase F replaces
 *  with the SwiftUI glass chat surface. */
export type UserChannel = {
  speak(text: string): Promise<void>
  awaitConfirm(prompt: string, defaultChoice?: 'yes' | 'no'): Promise<boolean>
  notifyProgress(step: number, total: number, label: string): Promise<void>
  notifyComplete(serviceName: string, summary: string): Promise<void>
  notifyFailed(serviceName: string, error: string, remedy?: string): Promise<void>
}

/** Result of running a complete setup flow. */
export type SetupFlowResult = {
  flow_id: string
  service_name: string
  status: 'success' | 'failed' | 'cancelled'
  duration_ms: number
  steps_completed: number
  steps_total: number
  installed_server_id?: string
  registered_tools?: string[]
  error?: string
}
