// codexHome.ts — A0 of the Codex migration: generate an ISOLATED CODEX_HOME with
// the config.toml that wires codex to our hidden proxy + in-process MCP server,
// resolve the codex binary (dev=homebrew, ship=vendored pinned), and emit the
// arch-dispatch shim for the ship bundle. Pure + filesystem halves are split so
// the architecture-critical config generation is unit-tested without a key.
//
// We NEVER touch the user's ~/.codex (it has a broken [[hooks]] config in 0.133
// and is theirs). Everything lives under state/codex/. See docs/clicky-migration/
// 01, 08, 12, 14 §A/§B, 15 (protocol findings).

import { mkdirSync, writeFileSync, existsSync, chmodSync } from "node:fs"
import { join } from "node:path"
import { spawnSync } from "node:child_process"

// ── arch dispatch (ship-time vendoring) ───────────────────────────────────────

/** macOS arch → the per-arch vendor triple HeyClicky uses. */
export function archTriple(arch: string = process.arch): string {
  switch (arch) {
    case "arm64": return "aarch64-apple-darwin"
    case "x64": return "x86_64-apple-darwin"
    default: throw new Error(`unsupported macOS arch for the vendored codex runtime: ${arch}`)
  }
}

/** The 648-byte-class POSIX shim that ships in the bundle: detect arch, prepend
 *  the vendored `path/` (bundled rg) to PATH, exec the per-arch codex. Mirrors
 *  HeyClicky's CodexRuntime/bin/codex. */
export function archDispatchShim(): string {
  return `#!/bin/sh
set -eu
SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
case "$(uname -m)" in
  arm64)  TRIPLE="aarch64-apple-darwin" ;;
  x86_64) TRIPLE="x86_64-apple-darwin" ;;
  *) echo "KAIROS: unsupported macOS arch $(uname -m) for the vendored codex runtime" >&2; exit 1 ;;
esac
PATH_DIR="\${SCRIPT_DIR}/../vendor/\${TRIPLE}/path"
[ -d "\${PATH_DIR}" ] && export PATH="\${PATH_DIR}:\${PATH:-}"
exec "\${SCRIPT_DIR}/../vendor/\${TRIPLE}/codex/codex" "$@"
`
}

/** Resolve which codex binary to run. Order: explicit override → vendored pin
 *  (ship) → homebrew (dev). Throws if none exist — we never silently fall back to
 *  an unknown PATH codex. `exists` is injected for testability. */
export function resolveCodexBinary(opts: {
  override?: string
  vendored?: string
  homebrew?: string
  exists?: (p: string) => boolean
}): string {
  const exists = opts.exists ?? existsSync
  for (const c of [opts.override, opts.vendored, opts.homebrew]) {
    if (c && exists(c)) return c
  }
  throw new Error("no codex binary found (override/vendored/homebrew all missing) — install codex or vendor the pinned runtime")
}

// ── TOML generation ───────────────────────────────────────────────────────────

/** Escape a value for a TOML basic string. Closes openclicky's R8 injection bug:
 *  control chars (\n \r \t) + the quote + backslash, so a hostile path/value can't
 *  break out of its string and inject config keys. */
export function tomlEscape(v: string): string {
  return v
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t")
}

export interface ConfigOpts {
  workspaceDir: string
  /** The proxy base_url codex points at (dev: localhost facade; ship: Worker). */
  baseUrl: string
  /** Env var the child reads for the per-install proxy token (NOT a provider key). */
  brainKeyEnv: string
  /** The single model alias the proxy maps to the real slug (e.g. MiniMax). */
  modelAlias: string
  /** The in-process MCP server URL (the daemon's /mcp on 127.0.0.1:9876). */
  mcpUrl: string
  /** Env var the child reads for the MCP bearer token. */
  mcpTokenEnv: string
}

/** Generate config.toml. Encodes the locked architecture decisions:
 *  - hidden provider speaking the Responses API (codex 0.133 rejects "chat");
 *  - one model alias (effort is set PER TURN on turn/start, NOT via [profiles.*]);
 *  - HTTP MCP server (url + bearer_token_env_var) — the in-process daemon server;
 *  - pre-trusted workspace + suppressed full-access warning;
 *  - sandbox_mode = workspace-write DEFAULT (never danger-full-access; 14 §B7).
 *  Per-turn/thread overrides (effort, model, sandbox elevation) ride the JSON-RPC,
 *  not this file. */
export function generateConfigToml(o: ConfigOpts): string {
  const ws = tomlEscape(o.workspaceDir)
  return `# GENERATED by KAIROS (codexHome.ts) — do not hand-edit; regenerated at boot.
model_provider = "kairos"
model = "${tomlEscape(o.modelAlias)}"
sandbox_mode = "workspace-write"
history.persistence = "save-all"

[model_providers.kairos]
name = "KAIROS"
base_url = "${tomlEscape(o.baseUrl)}"
env_key = "${tomlEscape(o.brainKeyEnv)}"
wire_api = "responses"

[mcp_servers.kairos]
url = "${tomlEscape(o.mcpUrl)}"
bearer_token_env_var = "${tomlEscape(o.mcpTokenEnv)}"

[projects."${ws}"]
trust_level = "trusted"

[notice]
hide_full_access_warning = true
`
}

// ── filesystem: build the isolated home ───────────────────────────────────────

export interface CodexHomeOpts extends Omit<ConfigOpts, "workspaceDir"> {
  /** Root under which home/ + workspace/ live (e.g. <repo>/state/codex). */
  root: string
}

export interface CodexHomeResult {
  home: string
  workspace: string
  configPath: string
}

/** Create (idempotently) the isolated CODEX_HOME + a git-init'd workspace +
 *  a chmod-600 config.toml. Safe to delete-and-regenerate. */
export async function ensureCodexHome(o: CodexHomeOpts): Promise<CodexHomeResult> {
  const home = join(o.root, "home")
  const workspace = join(o.root, "workspace")
  mkdirSync(home, { recursive: true, mode: 0o700 })
  mkdirSync(workspace, { recursive: true })
  try { chmodSync(home, 0o700) } catch { /* best-effort on odd filesystems */ }

  // codex refuses to run outside a git repo — init the workspace once.
  if (!existsSync(join(workspace, ".git"))) {
    spawnSync("git", ["init", "-q"], { cwd: workspace, stdio: "ignore" })
  }

  const configPath = join(home, "config.toml")
  writeFileSync(configPath, generateConfigToml({ ...o, workspaceDir: workspace }), { mode: 0o600 })
  try { chmodSync(configPath, 0o600) } catch { /* */ }

  return { home, workspace, configPath }
}
